spring:
  datasource:
    username: root
    password: 1qaz@WSX3edc
    url: jdbc:mysql://mysql.mayongfeng.cc:33306/mall_wms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: mayongfeng.cc:8848
#  application:
#    name: mall-ware

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 11000