spring:
  datasource:
    username: root
    password: 1qaz@WSX3edc
    url: jdbc:mysql://mysql.mayongfeng.cc:33306/mall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: mayongfeng.cc:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss	
#  application:
#    name: mall-product
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 10000
logging:
  level:
    com.may.mall: debug
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000