spring:
  cloud:
    nacos:
      discovery:
        server-addr: mayongfeng.cc:8848
    alicloud:
      access-key: LTAI4GEv7uPoJqWd7e8i3AHg
      secret-key: 1QGok71R4AqDbTpno0syp0M3vt64ha
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: may-image

  application:
    name: mall-third-party

server:
  port: 30000